### ISSUE TITLE
Replace `advice` to `description` in errors and make it optional

### ISSUE THREAD

**Issue by frkam** [youtogether-online/backend#50]
- [x] I have searched the [issues](https://github.com/youtogether-online/backend/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦

"Description" is a broader term that can include both advice for the user and other useful information. 

Not always an error needs advice or description for user, so we should make it optional in openapi docs.

**Comment by wtkeqrf0** [comment]
`message` field has been renamed to `Description`. Also, an error `code` has been added. He indicates the presence of the `description`, `advice` and `fields` fields (only on `validation` value).
