### ISSUE TITLE
Fallback to default language

### ISSUE THREAD

**Issue by frkam** [youtogether-online/backend#51]
- [x] I have searched the [issues](https://github.com/youtogether-online/backend/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦

1. Needs to change accepted languages to en-* (en-US and etc) and ru-* languages, see [language codes](https://www.w3.org/International/ms-lang.html)
2. If we don't support user's language we should use fallback language (english) as user language

**Comment by wtkeqrf0** [comment]
Accept-Language now handles correctly
