### ISSUE TITLE
GET /auth/session returns incorrect value

### ISSUE THREAD

**Issue by frkam** [youtogether-online/backend#66]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/youtogether-online/backend/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior 🤔

Accordingly to actual openapi docs, expected session.role to be "user" | "admin"

## Current Behavior 😯

Currently session.role is "USER" | "ADMIN"

**Comment by wtkeqrf0** [comment]
Can u re-create postgreSQL tables. Maybe you used old value from db.

New enum values are always will be lowercase
